src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Logged_at__c</fullName>
        <label>Logged at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoggerTest.cls
@isTest
private class LoggerTest {
    @isTest
    private static void testLogGeneric() {
        Profile adminProfile = [
            SELECT Id 
            FROM Profile 
            WHERE Name = 'System Administrator'
            LIMIT 1
        ];
        User adminUser = new User(
            Alias = 'adm',
            Country = 'United Kingdom',
            Email = 'adm.user@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'admin',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'adm.user@test.com'
        );
        insert adminUser;

        Test.startTest();
        System.runAs(adminUser) {
            Logger.log(Logger.LogSeverity.DEBUG, 'Test Debug message');
        }
        Logger.commitLogs();
        Test.stopTest();
        
        Log__c log = [
            SELECT Id,
                   Severity__c,
                   Message__c,
                   Running_User__c,
                   Logged_at__c
            FROM Log__c
            LIMIT 1
        ];

        System.assertEquals('DEBUG', log.Severity__c);
        System.assertEquals('Test Debug message', log.Message__c);
        System.assertEquals(adminUser.Id, log.Running_User__c);
        System.assertNotEquals(null, log.Logged_at__c);
    }

    @isTest
    private static void testLogSpecified() {
        Test.startTest();
        Logger.logSuccess('Test Success message');
        Logger.logError('Test Error message');
        Logger.logInfo('Test Info message');
        Logger.commitLogs();
        Test.stopTest();
        
        Integer logsCount = [
            SELECT COUNT()
            FROM Log__c
        ];

        System.assertEquals(3, logsCount);
    }
}